# Generated by Django 3.0.1 on 2020-01-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=120)),
                ('c_desc', models.TextField(blank=True)),
                ('c_type', models.CharField(default='None', max_length=100)),
                ('c_url', models.URLField(blank=True)),
                ('c_logo', models.ImageField(blank=True, upload_to='c_logos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
